input_default_gamepad_button(gp_face1, "face1");
input_default_gamepad_button(gp_face2, "face2");
input_default_gamepad_button(gp_face3, "face3");
input_default_gamepad_button(gp_face4, "face4");
input_default_gamepad_button(gp_padd, "padd");
input_default_gamepad_button(gp_padu, "padu");
input_default_gamepad_button(gp_padl, "padl");
input_default_gamepad_button(gp_padr, "padr");
input_default_gamepad_button(gp_shoulderl, "shoulderl");
input_default_gamepad_button(gp_shoulderr, "shoulderr");
input_default_gamepad_button(gp_shoulderlb, "shoulderlb");
input_default_gamepad_button(gp_shoulderrb, "shoulderrb");
input_default_gamepad_axis(gp_axislh, false, "axislh");
input_default_gamepad_axis(gp_axislv, false, "axislv");
input_default_gamepad_axis(gp_axisrh, false, "axisrh");
input_default_gamepad_axis(gp_axisrv, false, "axisrv");
input_default_gamepad_button(gp_start, "start");
input_default_gamepad_button(gp_select, "select");
input_default_gamepad_button(gp_stickl, "stickl");
input_default_gamepad_button(gp_stickr, "stickr");