//Needs to match simple types in global.__input_simple_type_lookup

global.__input_icons = {
    
    //Optional remapping for keyboard and mouse
    "keyboard and mouse": {
        
    },
    
    //Fallback gamepad icons
    //These are used when a gamepad is not recognised or an icon definition doesn't exist for a specific gamepad type
    "gamepad fallback": {
        "gamepad face south":         "A",
        "gamepad face east":          "B",
        "gamepad face west":          "X",
        "gamepad face north":         "Y",
        "gamepad shoulder l":         "LB",
        "gamepad shoulder r":         "RB",
        "gamepad trigger l":          "LT",
        "gamepad trigger r":          "RT",
        "gamepad select":             "view",
        "gamepad start":              "menu",
        "gamepad thumbstick l click": "thumbstick l click",
        "gamepad thumbstick r click": "thumbstick r click",
        "gamepad dpad up":            "dpad up",
        "gamepad dpad down":          "dpad down",
        "gamepad dpad left":          "dpad left",        
        "gamepad dpad right":         "dpad right",
        
        "gamepad thumbstick l left":  "thumbstick l left",
        "gamepad thumbstick l right": "thumbstick l right",
        "gamepad thumbstick l up":    "thumbstick l up",
        "gamepad thumbstick l down":  "thumbstick l down",
        "gamepad thumbstick r left":  "thumbstick r left",
        "gamepad thumbstick r right": "thumbstick r right",
        "gamepad thumbstick r up":    "thumbstick r up",
        "gamepad thumbstick r down":  "thumbstick r down",
        
        "gamepad guide":              "guide",
        "gamepad misc 1":             "misc 1",
        "gamepad touchpad click":     "touchpad click",
        "gamepad paddle 1":           "paddle 1",
        "gamepad paddle 2":           "paddle 2",
        "gamepad paddle 3":           "paddle 3",
        "gamepad paddle 4":           "paddle 4",
    },
    
    //Xbox One controllers
    "xbox one": {
        "gamepad face south":         "A",
        "gamepad face east":          "B",
        "gamepad face west":          "X",
        "gamepad face north":         "Y",
        "gamepad shoulder l":         "LB",
        "gamepad shoulder r":         "RB",
        "gamepad trigger l":          "LT",
        "gamepad trigger r":          "RT",
        "gamepad select":             "view",
        "gamepad start":              "menu",
        "gamepad thumbstick l click": "thumbstick l click",
        "gamepad thumbstick r click": "thumbstick r click",
        "gamepad dpad up":            "dpad up",
        "gamepad dpad down":          "dpad down",
        "gamepad dpad left":          "dpad left",        
        "gamepad dpad right":         "dpad right",
        
        //These are used for Elite controllers
        "gamepad paddle 1":           "paddle 1",
        "gamepad paddle 2":           "paddle 2",
        "gamepad paddle 3":           "paddle 3",
        "gamepad paddle 4":           "paddle 4",
        
        "gamepad thumbstick l left":  "thumbstick l left",
        "gamepad thumbstick l right": "thumbstick l right",
        "gamepad thumbstick l up":    "thumbstick l up",
        "gamepad thumbstick l down":  "thumbstick l down",
        "gamepad thumbstick r left":  "thumbstick r left",
        "gamepad thumbstick r right": "thumbstick r right",
        "gamepad thumbstick r up":    "thumbstick r up",
        "gamepad thumbstick r down":  "thumbstick r down",
    },
    
    //PlayStation 5
    "ps5": {
        "gamepad face south":         "cross",
        "gamepad face east":          "circle",
        "gamepad face west":          "square",
        "gamepad face north":         "triangle",
        "gamepad shoulder l":         "L1",
        "gamepad shoulder r":         "R1",
        "gamepad trigger l":          "L2",
        "gamepad trigger r":          "R2",
        "gamepad select":             "create",
        "gamepad start":              "options",
        "gamepad thumbstick l click": "L3",
        "gamepad thumbstick r click": "R3",
        "gamepad dpad up":            "dpad up",
        "gamepad dpad down":          "dpad down",
        "gamepad dpad left":          "dpad left",        
        "gamepad dpad right":         "dpad right",
        
        "gamepad thumbstick l left":  "thumbstick l left",
        "gamepad thumbstick l right": "thumbstick l right",
        "gamepad thumbstick l up":    "thumbstick l up",
        "gamepad thumbstick l down":  "thumbstick l down",
        "gamepad thumbstick r left":  "thumbstick r left",
        "gamepad thumbstick r right": "thumbstick r right",
        "gamepad thumbstick r up":    "thumbstick r up",
        "gamepad thumbstick r down":  "thumbstick r down",
        
        "gamepad touchpad click": "touchpad click",
    },
    
    //Switch handheld/dual JoyCon/Pro Controller
    "switch": {
        "gamepad face south":         "B",
        "gamepad face east":          "A",
        "gamepad face west":          "X",
        "gamepad face north":         "Y",
        "gamepad shoulder l":         "L",
        "gamepad shoulder r":         "R",
        "gamepad trigger l":          "ZL",
        "gamepad trigger r":          "ZR",
        "gamepad select":             "plus",
        "gamepad start":              "minus",
        "gamepad thumbstick l click": "LS",
        "gamepad thumbstick r click": "RS",
        "gamepad dpad up":            "dpad up",
        "gamepad dpad down":          "dpad down",
        "gamepad dpad left":          "dpad left",        
        "gamepad dpad right":         "dpad right",
        
        "gamepad guide":              "home",
        "gamepad misc 1":             "capture",
        
        "gamepad thumbstick l left":  "thumbstick l left",
        "gamepad thumbstick l right": "thumbstick l right",
        "gamepad thumbstick l up":    "thumbstick l up",
        "gamepad thumbstick l down":  "thumbstick l down",
        "gamepad thumbstick r left":  "thumbstick r left",
        "gamepad thumbstick r right": "thumbstick r right",
        "gamepad thumbstick r up":    "thumbstick r up",
        "gamepad thumbstick r down":  "thumbstick r down",
    },
    
    //Left-hand Switch JoyCon
    //This setup assums horizontal hold type
    "switch joycon left": {
        "gamepad face south":         "face south",
        "gamepad face east":          "face east",
        "gamepad face west":          "face west", 
        "gamepad face north":         "face north",
        "gamepad shoulder l":         "SL",
        "gamepad shoulder r":         "SR",
        "gamepad select":             "capture",
        "gamepad start":              "minus",
        "gamepad thumbstick l click": "LS",
        
        "gamepad thumbstick l left":  "thumbstick left",
        "gamepad thumbstick l right": "thumbstick right",
        "gamepad thumbstick l up":    "thumbstick up",
        "gamepad thumbstick l down":  "thumbstick down",
    },
    
    //Right-hand Switch JoyCon
    //This setup assums horizontal hold type
    "switch joycon right": {
        "gamepad face south":         "face south",
        "gamepad face east":          "face east",
        "gamepad face west":          "face west", 
        "gamepad face north":         "face north",
        "gamepad shoulder l":         "SL",
        "gamepad shoulder r":         "SR",
        "gamepad select":             "home",
        "gamepad start":              "plus",
        "gamepad thumbstick l click": "LS",
        
        "gamepad thumbstick l left":  "thumbstick left",
        "gamepad thumbstick l right": "thumbstick right",
        "gamepad thumbstick l up":    "thumbstick up",
        "gamepad thumbstick l down":  "thumbstick down",
    },
    
    //Xbox 360
    "xbox 360": {
        "gamepad face south":         "A",
        "gamepad face east":          "B",
        "gamepad face west":          "X",
        "gamepad face north":         "Y",
        "gamepad shoulder l":         "LB",
        "gamepad shoulder r":         "RB",
        "gamepad trigger l":          "LT",
        "gamepad trigger r":          "RT",
        "gamepad select":             "back",
        "gamepad start":              "start",
        "gamepad thumbstick l click": "thumbstick l click",
        "gamepad thumbstick r click": "thumbstick r click",
        "gamepad dpad up":            "dpad up",
        "gamepad dpad down":          "dpad down",
        "gamepad dpad left":          "dpad left",        
        "gamepad dpad right":         "dpad right",
        
        "gamepad thumbstick l left":  "thumbstick l left",
        "gamepad thumbstick l right": "thumbstick l right",
        "gamepad thumbstick l up":    "thumbstick l up",
        "gamepad thumbstick l down":  "thumbstick l down",
        "gamepad thumbstick r left":  "thumbstick r left",
        "gamepad thumbstick r right": "thumbstick r right",
        "gamepad thumbstick r up":    "thumbstick r up",
        "gamepad thumbstick r down":  "thumbstick r down",
    },
    
    //PlayStation 4
    "ps4": {
        "gamepad face south":         "cross",
        "gamepad face east":          "circle",
        "gamepad face west":          "square",
        "gamepad face north":         "triangle",
        "gamepad shoulder l":         "L1",
        "gamepad shoulder r":         "R1",
        "gamepad trigger l":          "L2",
        "gamepad trigger r":          "R2",
        "gamepad select":             "share",
        "gamepad start":              "options",
        "gamepad thumbstick l click": "L3",
        "gamepad thumbstick r click": "R3",
        "gamepad dpad up":            "dpad up",
        "gamepad dpad down":          "dpad down",
        "gamepad dpad left":          "dpad left",        
        "gamepad dpad right":         "dpad right",
        
        "gamepad thumbstick l left":  "thumbstick l left",
        "gamepad thumbstick l right": "thumbstick l right",
        "gamepad thumbstick l up":    "thumbstick l up",
        "gamepad thumbstick l down":  "thumbstick l down",
        "gamepad thumbstick r left":  "thumbstick r left",
        "gamepad thumbstick r right": "thumbstick r right",
        "gamepad thumbstick r up":    "thumbstick r up",
        "gamepad thumbstick r down":  "thumbstick r down",
        
        "gamepad touchpad click": "touchpad click",
    },
    
    //Nintendo Gamecube
    "gamecube": {
        "gamepad face south":         "A",
        "gamepad face east":          "X",
        "gamepad face west":          "B",
        "gamepad face north":         "Y",
        "gamepad shoulder r":         "Z",
        "gamepad trigger l":          "L",
        "gamepad trigger r":          "R",
        "gamepad start":              "start",
        "gamepad dpad up":            "dpad up",
        "gamepad dpad down":          "dpad down",
        "gamepad dpad left":          "dpad left",        
        "gamepad dpad right":         "dpad right",
        
        "gamepad thumbstick l left":  "thumbstick l left",
        "gamepad thumbstick l right": "thumbstick l right",
        "gamepad thumbstick l up":    "thumbstick l up",
        "gamepad thumbstick l down":  "thumbstick l down",
        "gamepad thumbstick r left":  "thumbstick r left",
        "gamepad thumbstick r right": "thumbstick r right",
        "gamepad thumbstick r up":    "thumbstick r up",
        "gamepad thumbstick r down":  "thumbstick r down",
    },
    
    //PlayStation 4
    "psx": {
        "gamepad face south":         "cross",
        "gamepad face east":          "circle",
        "gamepad face west":          "square",
        "gamepad face north":         "triangle",
        "gamepad shoulder l":         "L1",
        "gamepad shoulder r":         "R1",
        "gamepad trigger l":          "L2",
        "gamepad trigger r":          "R2",
        "gamepad select":             "select",
        "gamepad start":              "start",
        "gamepad thumbstick l click": "L3",
        "gamepad thumbstick r click": "R3",
        "gamepad dpad up":            "dpad up",
        "gamepad dpad down":          "dpad down",
        "gamepad dpad left":          "dpad left",        
        "gamepad dpad right":         "dpad right",
        
        "gamepad thumbstick l left":  "thumbstick l left",
        "gamepad thumbstick l right": "thumbstick l right",
        "gamepad thumbstick l up":    "thumbstick l up",
        "gamepad thumbstick l down":  "thumbstick l down",
        "gamepad thumbstick r left":  "thumbstick r left",
        "gamepad thumbstick r right": "thumbstick r right",
        "gamepad thumbstick r up":    "thumbstick r up",
        "gamepad thumbstick r down":  "thumbstick r down",
    },
    
    //Nintendo 64
    "n64": {
        "gamepad face south":         "A",
        "gamepad face east":          "B",
        "gamepad shoulder l":         "L",
        "gamepad shoulder r":         "R",
        "gamepad trigger l":          "Z",
        "gamepad start":              "start",
        "gamepad dpad up":            "dpad up",
        "gamepad dpad down":          "dpad down",
        "gamepad dpad left":          "dpad left",        
        "gamepad dpad right":         "dpad right",
        
        "gamepad thumbstick l left":  "thumbstick left",
        "gamepad thumbstick l right": "thumbstick right",
        "gamepad thumbstick l up":    "thumbstick up",
        "gamepad thumbstick l down":  "thumbstick down",
        "gamepad thumbstick r left":  "C left",
        "gamepad thumbstick r right": "C right",
        "gamepad thumbstick r up":    "C up",
        "gamepad thumbstick r down":  "C down",
    },
    
    //Sega Saturn
    "saturn": {
        "gamepad face south": "A",
        "gamepad face east":  "B",
        "gamepad face west":  "X",
        "gamepad face north": "Y",
        "gamepad shoulder l": "L",
        "gamepad shoulder r": "Z",
        "gamepad trigger l":  "L",
        "gamepad trigger r":  "C",
        "gamepad start":      "start",
        "gamepad dpad up":    "dpad up",
        "gamepad dpad down":  "dpad down",
        "gamepad dpad left":  "dpad left",        
        "gamepad dpad right": "dpad right",
    },
    
    //Super Nintendo
    "snes": {
        "gamepad face south": "B",
        "gamepad face east":  "A",
        "gamepad face west":  "Y",
        "gamepad face north": "X",
        "gamepad shoulder l": "L",
        "gamepad shoulder r": "R",
        "gamepad select":     "select",
        "gamepad start":      "start",
        "gamepad dpad up":    "dpad up",
        "gamepad dpad down":  "dpad down",
        "gamepad dpad left":  "dpad left",        
        "gamepad dpad right": "dpad right",
    },
};