// Feather disable all

#macro INPUT_CURSOR_ROOM_SPACE    0
#macro INPUT_CURSOR_GUI_SPACE     1
#macro INPUT_CURSOR_DEVICE_SPACE  2

#macro INPUT_CURSOR_LIMIT_NONE      0
#macro INPUT_CURSOR_LIMIT_BOUNDARY  1
#macro INPUT_CURSOR_LIMIT_AABB      2
#macro INPUT_CURSOR_LIMIT_CIRCLE    3