var _string = "";
_string += "up = "         + string(input_check("up"    )) + "\n";
_string += "down = "       + string(input_check("down"  )) + "\n";
_string += "left = "       + string(input_check("left"  )) + "\n";
_string += "right = "      + string(input_check("right" )) + "\n";
_string += "accept = "     + string(input_check("accept")) + "\n";
_string += "cancel = "     + string(input_check("cancel")) + "\n";
_string += "\n";
_string += "Last combo = " + string(last_combo) + "\n";
_string += "\n";
_string += "Combo \"konami\" phase = "             + string(input_combo_get_phase("konami"            )) + "/" + string(input_combo_get_phase_count("konami"            )) + "\n";
_string += "Combo \"sweep right->up\" phase = "    + string(input_combo_get_phase("sweep right->up"   )) + "/" + string(input_combo_get_phase_count("sweep right->up"   )) + "\n";
_string += "Combo \"power attack right\" phase = " + string(input_combo_get_phase("power attack right")) + "/" + string(input_combo_get_phase_count("power attack right")) + "\n";
_string += "Combo \"fireball\" phase = "           + string(input_combo_get_phase("fireball"          )) + "/" + string(input_combo_get_phase_count("fireball"          )) + "\n";
draw_text(10, 10, _string);